# wxmplot documentation build configuration file
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import os
import sys
from datetime import date

from packaging.version import parse as version_parse

import sitka_spruce

project = 'Sitka Spruce'
copyright = f'{date.today()}, Matthew Newville, The University of Chicago'

release = version_parse(sitka_spruce.__version__).base_version

html_title = "Sitka Spruce: Heirarchical Data Browser"
html_short_title = "Sitka Spruce"

# sys.path.append(os.path.abspath(os.path.join('.')))

extensions = ['sphinx.ext.autodoc', 'sphinx.ext.mathjax',
              'sphinx.ext.napoleon', 'sphinxcontrib.video',
              'sphinx_copybutton',
              "sphinx_design",
              "nbsphinx" ]


# autoclass_content = 'both'
templates_path = ['_templates']
source_suffix = {'.rst': 'restructuredtext'}

exclude_trees = ['_build']
default_role = None
source_encoding = 'utf-8'

add_function_parentheses = True

add_module_names = True
pygments_style = 'sphinx'

html_theme_path = ['sphinx_theme']
html_theme = 'bizstyle'


html_static_path = ['_static']
html_sidebars = {
  'index': ["indexsidebar.html",  "sourcelink.html", "searchbox.html"],
  "*": [ "localtoc.html",  "relations.html", "sourcelink.html", "searchbox.html"]
}

html_domain_indices = False
html_use_index = True
html_show_sourcelink = True

latex_documents = [('index', 'sitka_spruce.tex', 'Sitka Spruce documentation',
                    'Matthew Newville', 'manual')]
